marvelous-monkeys/Grace-Shopper

- README.md
> added a new line to README

- README.md
> rob merge test

- README.md
> wrote my name in README

- .travis.yml
- client/app.js
- client/components/ProductList.js
- client/store/index.js
- client/store/products.js
- package.json
- script/seed.js
- server/api/index.js
- server/api/products.js
- server/db/models/index.js
- server/db/models/products.js
> Feature: Product List Backend and Frontend completed

- client/components/auth-form.js
- client/store/user.js
- package-lock.json
- package.json
- server/api/users.js
- server/db/db.js
- server/db/models/address.js
- server/db/models/index.js
- server/db/models/user.js
- server/index.js
> User model

- script/seed.js
- server/db/models/user.js
> issue with firstname and lastname not empty

- client/components/auth-form.js
- client/store/user.js
- script/seed.js
- server/api/users.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/orderProduct.js
- server/db/models/user.js
> Orders model

- client/components/product-list.spec.js
- client/store/products.spec.js
- server/api/products.spec.js
- server/api/users.spec.js
- server/db/models/products.spec.js
- server/db/models/user.spec.js
* [x ] added unit tests (or none needed)
---
Wrote tests for "ProductList" back-end and front-end. We have 11/11 tests passing.
> merged ProductList-tests with master

- client/app.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- server/db/models/products.js
- server/index.js
> Product list homepage view only

- client/components/cart.js
- client/components/cartListItem.js
- client/store/cart.js
- package-lock.json
- public/index.html
> created cart add/remove functionality

- server/api/products.js
- server/db/models/user.js
> route validations done

- client/components/Checkout.js
- client/routes.js
- client/store/user.js
- server/auth/index.js
- server/checkout/index.js
> Empty cart issue

- client/components/AdminPage.js
- client/store/products.spec.js
- server/api/products.spec.js
- server/api/users.spec.js
- server/db/models/user.spec.js
* [ x] added unit tests (or none needed)
---
> created backend api tests

- client/components/user-home.js
> order success and home screen bug fixed

- client/routes.js
> fixed admin route access

- server/auth/google.js
> implemented O-auth

- client/components/AdminPage.js
- client/components/EditProductForm.js
- client/store/singleProduct.js
- server/api/products.js
---
fixed update product feature to not overwrite other items
also added feature to not allow admin to delete themselves inside admin panel
> fixed update product feature to not overwrite other items

- server/auth/google.js
> O auth via heroku

- client/components/AdminPage.js
- client/components/Checkout.js
- client/components/EditProductForm.js
- client/components/ProductList.js
- client/components/auth-form.js
- client/components/navbar.js
- client/components/user-home.js
- public/index.html
- public/style.css
- script/seed.js
- server/api/products.spec.js
- server/api/users.spec.js
> updated css styling

- client/components/order_history/order_history.css
- public/style.css
- script/seed.js
> Updated seed
